services:

  payheure-backend:
    build: .
    container_name: payheure_backend_container
    ports:
      - "8080:8080"
    volumes:
      # Fichier .accdb existant sur l'hôte (UCanAccess n'a pas besoin de serveur de base de données).
      - C:/PayHeure:/data
    environment:
      SPRING_DATASOURCE_URL: "jdbc:ucanaccess:///data/payheureDb.accdb"
    networks:
      - payheure-net

  frontend:
    build: ./PayHeureUI
    container_name: payheure_frontend_container
    ports:
      - "4200:80"
    depends_on:
      - payheure-backend
    environment:
      API_BASE_URL: "http://localhost:8080/api"
    networks:
      - payheure-net

networks:
  payheure-net:
    driver: bridge
